// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearAppCache() {
  return window['go']['app']['App']['ClearAppCache']();
}

export function ClearBackgroundImage(arg1) {
  return window['go']['app']['App']['ClearBackgroundImage'](arg1);
}

export function CopyObject(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['app']['App']['CopyObject'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function CreateBucket(arg1, arg2, arg3) {
  return window['go']['app']['App']['CreateBucket'](arg1, arg2, arg3);
}

export function CreateConnection(arg1) {
  return window['go']['app']['App']['CreateConnection'](arg1);
}

export function DeleteBucket(arg1, arg2, arg3) {
  return window['go']['app']['App']['DeleteBucket'](arg1, arg2, arg3);
}

export function DeleteConnection(arg1) {
  return window['go']['app']['App']['DeleteConnection'](arg1);
}

export function DeleteObject(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['DeleteObject'](arg1, arg2, arg3, arg4);
}

export function DownloadDirectory(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['app']['App']['DownloadDirectory'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function DownloadFile(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['app']['App']['DownloadFile'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function DuplicateConnection(arg1) {
  return window['go']['app']['App']['DuplicateConnection'](arg1);
}

export function EditFile(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['EditFile'](arg1, arg2, arg3, arg4);
}

export function GetAllThemes() {
  return window['go']['app']['App']['GetAllThemes']();
}

export function GetBackgroundInfo(arg1) {
  return window['go']['app']['App']['GetBackgroundInfo'](arg1);
}

export function GetConnections() {
  return window['go']['app']['App']['GetConnections']();
}

export function GetCurrentTheme(arg1) {
  return window['go']['app']['App']['GetCurrentTheme'](arg1);
}

export function ListBuckets(arg1) {
  return window['go']['app']['App']['ListBuckets'](arg1);
}

export function ListObjects(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['ListObjects'](arg1, arg2, arg3, arg4, arg5);
}

export function MoveObject(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['app']['App']['MoveObject'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function PreviewFile(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['PreviewFile'](arg1, arg2, arg3, arg4);
}

export function SaveBackgroundImage(arg1, arg2) {
  return window['go']['app']['App']['SaveBackgroundImage'](arg1, arg2);
}

export function SaveOverlayOpacity(arg1, arg2) {
  return window['go']['app']['App']['SaveOverlayOpacity'](arg1, arg2);
}

export function SaveTheme(arg1, arg2, arg3) {
  return window['go']['app']['App']['SaveTheme'](arg1, arg2, arg3);
}

export function SelectDirectory() {
  return window['go']['app']['App']['SelectDirectory']();
}

export function SelectFile() {
  return window['go']['app']['App']['SelectFile']();
}

export function SelectSaveFile(arg1) {
  return window['go']['app']['App']['SelectSaveFile'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['app']['App']['TestConnection'](arg1);
}

export function UpdateConnection(arg1) {
  return window['go']['app']['App']['UpdateConnection'](arg1);
}

export function UploadFile(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['app']['App']['UploadFile'](arg1, arg2, arg3, arg4, arg5, arg6);
}
