// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';
import {obs} from '../models';
import {app} from '../models';

export function CopyObject(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<boolean>;

export function CreateBucket(arg1:string,arg2:string,arg3:string):Promise<boolean>;

export function CreateConnection(arg1:db.Connection):Promise<db.Connection>;

export function DeleteBucket(arg1:string,arg2:string,arg3:string):Promise<boolean>;

export function DeleteConnection(arg1:string):Promise<boolean>;

export function DeleteObject(arg1:string,arg2:string,arg3:string,arg4:string):Promise<boolean>;

export function DownloadDirectory(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;

export function DownloadFile(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<string>;

export function GetConnections():Promise<Array<db.Connection>>;

export function ListBuckets(arg1:string):Promise<Array<obs.Bucket>>;

export function ListObjects(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<app.ListObjectsResponse>;

export function MoveObject(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<boolean>;

export function SelectDirectory():Promise<string>;

export function SelectFile():Promise<string>;

export function SelectSaveFile(arg1:string):Promise<string>;

export function TestConnection(arg1:db.Connection):Promise<boolean>;

export function UpdateConnection(arg1:db.Connection):Promise<boolean>;

export function UploadFile(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<string>;
